version: '3'

services:
  seapostgres:
    image: postgres:9.6
    restart: always
    ports:
      - '5001:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seadb

  sea:
    image: pulawskk11/sportseventapi:latest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - seapostgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://seapostgres:5432/seadb?useSSL=false