insert into teams(id, name) values (1, 'Chelsea'),
                                   (2, 'Arsenal'),
                                   (3, 'Manchester United'),
                                   (4, 'Manchester City'),
                                   (5, 'Newcastle United'),
                                   (6, 'West Ham United'),
                                   (7, 'Crystal Palace'),
                                   (8, 'Aston Villa'),
                                   (9, 'Norwich'),
                                   (10, 'Leicester'),
                                   (11, 'Southampton'),
                                   (12, 'Sheffield United'),
                                   (13, 'Tottenham'),
                                   (14, 'Brighton'),
                                   (15, 'Everton'),
                                   (16, 'Liverpool'),
                                   (17, 'Watford'),
                                   (18, 'Wolverhampton Wanders'),
                                   (19, 'Bournemouth'),
                                   (20, 'Burnley');

insert into competitions(id, name) values (1, 'Premier League');

insert into team_competition(teams_id, competitions_id) values (1,1),
                                                               (2, 1),
                                                               (3, 1),
                                                               (4, 1),
                                                               (5, 1),
                                                               (6, 1),
                                                               (7, 1),
                                                               (8, 1),
                                                               (9, 1),
                                                               (10, 1),
                                                               (11, 1),
                                                               (12, 1),
                                                               (13, 1),
                                                               (14, 1),
                                                               (15, 1),
                                                               (16, 1),
                                                               (17, 1),
                                                               (18, 1),
                                                               (19, 1),
                                                               (20, 1);